apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "domain-4"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/data-console/domain-4.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd